### ISSUE TITLE
Dynamically created images cause slow page load

### ISSUE THREAD

**Issue by jsunsawyer** [nystudio107/craft3-imageoptimize#56]
[Dynamically](https://github.com/nystudio107/craft-imageoptimize#dynamically-creating-optimized-image-variants) creating optimized image variants causes slow page load times in my dev environment. With only a few images, my page load time goes from 250ms to just over 2.5s.

- Image Volume is on Amazon S3
- The dynamically transformed image has 2 other image optimize fields associated with it
- The images are **not** being replaced on S3 on each load

```
{% set optimizedImages = craft.imageOptimize.createOptimizedImages(
  image,
  [
    {
      'width': 555,
      'useAspectRatio': true,
      'aspectRatioX': 555,
      'aspectRatioY': 185,
      'retinaSizes': ['1', '2'],
      'quality': 82,
      'format': 'jpg',
    },
  ],
  true
) %}
<div style="background-color: {{ optimizedImages.colorPalette[0] }};">
  <img
    class="toolkit_widget-image lazyload"
    src="{{ optimizedImages.placeholderBox() }}"
    data-srcset="{{ optimizedImages.srcsetWidth(555, true) }}">
</div>
```

**Comment by khalwat** [comment]
This should be addressed in 1.4.22 -- give it a whirl?

https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.22

**Comment by jsunsawyer** [comment]
Load times are pretty similar to what they were. If I disable the colorPalette option, it's a bit faster. Maybe 200ms.

My original test used 3 different image sources. Adding 6 additional images, all of the same source from one of the first 3, gives me load times of about 6-7 seconds. (9 images total - 3 unique sources)

If I disable the colorPalette option with 9 images in, I get between 4-6 second load times.

**Update:** If I use images from my Image Optimize fields instead, my page load time goes to about 300ms total, with 9 images.

**Comment by khalwat** [comment]
huh, that's crazy. It should be disabling all of that entirely. Will have a look

**Comment by khalwat** [comment]
This should be addressed (for real) in 1.4.23:

https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.23

**Comment by jsunsawyer** [comment]
I'm still getting long page loads with that last update.

It seems that each image is adding around 1/2 a second to the load time.

**Comment by khalwat** [comment]
huh. Well, I'll leave the issue open, and set up a decent test suite locally, then.

In general, I still think it's best to use the OptimizedImages field for most things.

**Comment by jsunsawyer** [comment]
Sounds good. Just trying to avoid adding a field for a very specific use case. End up processing crops that never get used on 99% of images.

Let me know if you need any help testing/troubleshooting.

**Comment by khalwat** [comment]
I wonder if it could somehow be the `optipng` / `jpegoptim` tools that run after a transform is created.

**Comment by jsunsawyer** [comment]
I just set up this project on a new hackintosh install that I'm playing around with at home. With no image processors installed I am getting about 4-6 second load times. This is on a machine with an  i7 8700k cpu, so about as fast as I could probably run it.

**Comment by khalwat** [comment]
Give this a whirl @jsunsawyer  : https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.24

**Comment by jsunsawyer** [comment]
@khalwat It's still slow. Taking about 7.5s vs 450ms with native transforms.

**Comment by jsunsawyer** [comment]
We've set up our staging environment and ended up using imgix since transforms were crushing our server, causing stuck tasks. Tried to re-implement this and still getting long page loads. Just sticking with native transforms for misc crops for now.

**Comment by khalwat** [comment]
So I profiled this, and it's actually pretty funny what's happening. It's actually _not_ recreating the image variants, it's properly caching and returning them. So what's going on?

<img width="1077" alt="google chromescreensnapz110" src="https://user-images.githubusercontent.com/7570798/38449697-844ffbd6-39e0-11e8-8031-92ec0282e389.png">

To "prime the pump" I'm pre-fetching the image after the transform is created. Which happens synchronously:

            ImageOptimize::$transformClass::prefetchRemoteFile($url);

...and it does the same thing for the `.webp` variant as well:

            ImageOptimize::$transformClass::prefetchRemoteFile($webPUrl);

If we disable these, check out what the timings look like:

<img width="1077" alt="google chromescreensnapz111" src="https://user-images.githubusercontent.com/7570798/38449722-065d8e40-39e1-11e8-994a-d19c0f99a142.png">

We go from `443ms` to return the transformed images down to just `18.4ms`... or roughly `24x` faster.

Ooops. Expect an update soon. :)

**Comment by khalwat** [comment]
Fixed in 1.4.29: https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.4.29
